
knight: ShortestKnightPath.c
	cc ShortestKnightPath.c -o knight -lcriterion
	./knight

snail: snail.c
	cc snail.c -o snail -lcriterion
	./snail

genetic: BinaryGeneticAlgorithm.c
	cc BinaryGeneticAlgorithm.c -o genetic -lcriterion
	./genetic
